### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [Riverssen/Rivercoin#2]
Greetings @Tastazz  ,

I'm a Graphic Designer and I've reached you believing that a logo proposal would be helpful to this project!
A good logo that transmit a message its helpful when it comes to publicity, making it appealing to the eye.
If this is something of your interest, we can get started towards the logo-making process.

I'll be looking forward for your reply
Best Regards,
-Luigi.

**Comment by Riverssen** [comment]
Hello @LuigiBaute,

We currently have a UI/UX designer working on the project with us, if you are interested in joining then please contact me (Riverssen) on the discord, or through my email (Riverssen@gmail.com)

Thanks.
